# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: 'true'
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      TORCH_TEST: 1

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Get Date
        id: get-date
        shell: bash
        run: |
          echo "::set-output name=year-week::$(date -u "+%Y-%U")"
          echo "::set-output name=date::$(date -u "+%F")"

      - name: Restore R package cache
        uses: actions/cache@v2
        id: r-package-cache
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ubuntu-latest-${{ steps.get-date.outputs.year-week }}

      - name: Install remotes
        if: steps.r-package-cache.outputs.cache-hit != 'true'
        run: install.packages("remotes")

      - name: Install system dependencies
        shell: bash
        run: |
          . /etc/os-release
          while read -r cmd
          do
            echo "$cmd"
            sudo $cmd
          done < <(Rscript -e "writeLines(remotes::system_requirements('$ID-$VERSION_ID'))")

      - name: Install Package + deps
        run: remotes::install_local(dependencies = TRUE, force = TRUE)

      - name: Install Miniconda
        run: reticulate::install_miniconda()

      - name: Install Tensorflow + Keras deps
        run: keras::install_keras(tensorflow = 'default-cpu')

      - name: Install LibTorch
        run: torch::install_torch()

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr
          needs: coverage

      - name: Test coverage
        run: covr::codecov(quiet = FALSE)
        shell: Rscript {0}
